# Use OpenJDK base image
FROM openjdk:11-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Maven to the Docker image
COPY target/com.ameyrupji.helloworld-1.0-SNAPSHOT.jar /app/app.jar

# Expose port 8080
EXPOSE 8080

# Set the entry point for the container
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
